[project]
name = "mcp-server-demo"
version = "0.1.0"
description = " Showcasing a demo about MCP server creation with mcp-python-sdk"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.7.1",
]
